app:
  name: order-service
  version: 1.0.0

http:
  port: 8080

postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: order
  ssl_mode: disable

redis:
  host: localhost
  port: 6380
  password:
  db: 0

kafka:
  host: localhost
  port: 9092
  topic: order
  group_id: order-consumer